DWAPlannerROS:

  max_vel_x: 0.25
  min_vel_x: -0.25

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 0.3
  min_trans_vel: -0.3

  max_rot_vel: 0.8
  min_rot_vel: -0.8

  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 1

  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40
  controller_frequency: 3.0

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  oscillation_reset_dist: 0.05

  publish_traj_pc: true
  publish_cost_grid_pc: true
